apiVersion: v1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeU1ERXpNREV3TlRZd01Wb1hEVE15TURFeU9URXdOVFl3TVZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTEswCnlHSUMxRmpvSko2c1FZSzZEWXBMUm15ckFLdmJpWFBqTmMzNGkxdUxjemN1dE1LWVJwM3IvSmFnYnBpSmZpWXAKNFF4ZGs3UldTVGJKaURLQ1VpT3NaTmRaVXNsRDlRK1UwYnFQNmZFTlI4Sk1zWjJGOCsyM2RpdTZUSFMxb3lHcQpzNlJCRUdSTkRGNlhYT2tRQnM4dzNXeDhHOVBaSVg0bkxtVi9NUzg5TlU5YVlGNklQeXdSUzI0RU5PQUxVampZCmprVXJ5eUY4N1BoaktqeTllUTlFQTR6WDdFYmFuK1c4QmdMTi91TGV1dE5JZ0dqNTUzT2JuRmhLVmVqMUkxWjEKNVI0MjhMc1ZldkhvNmFZSlN6NDkwRUNXU1piWmNGNmtMVHdzYzQwNTF6UU1GS3p3Zy8yREVscWtsb2Q0RENJWQo3UTJuRTdXMm5vdmU3TkVNT3hrQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJTTGtTQzFsZXVvZExoWENIN0oyblpwUi9VNktEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFJYmFYK08xWApldXM1K0hXZTlGOTRRR2hqUTlmRVc3RmNkYi9ONW1sektEaWQ0dU5WVWhBQW9HYXhvUm5rSllTNS9ZOFJjRVhBCkIrU0hUSGFvR2NPQlVVWE9XU0pidU1OWDB4V2RXVW9GemNVNDVhelI4b2JZRDZkYlgzUEh0MEh1WWhibGxEU1AKNU56V09qTlhYcFh6dXVFTnBpdUU1TFMwZjhpVEVlTWpQOE9ya0lmZFk0UkhhUHlhc2phQ1g3SlVRUTkyM24ySwo0ODk0aTMxNXhRd0Qxd2ticmsrbjdEQ04ycEpvS1cvL0lNb2xwd3UwMTE5blZtd2lZbEgvQklIREN1bG1yNDFDCjFnaVZybmdhbFROQTJRWWVFQVU5WU42dStwUmRVWThjZXQwWTBpOCtRUGJuS2VJM2FrMDd5bnFveEp4ZGcrWDUKWEc5RjRSbmU0MlpwMXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  namespace: Z3Vlc3Rib29r
  token: ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltWjZjMGwyWVhsalpsVnZOVzQwVm5ZMmJXRXpXbEE1WmpVM1NFUndTVTltUm5SRmFHdHFiVVJDY1dzaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUpuZFdWemRHSnZiMnNpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxZM0psZEM1dVlXMWxJam9pWkdWbVlYVnNkQzEwYjJ0bGJpMDNkM0UxWWlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKa1pXWmhkV3gwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXpaWEoyYVdObExXRmpZMjkxYm5RdWRXbGtJam9pTXpZeFptUXdNVEF0WkdVM05DMDBObVZoTFdJek1tSXROMlkzWmpCa1lUTTFaVGN4SWl3aWMzVmlJam9pYzNsemRHVnRPbk5sY25acFkyVmhZMk52ZFc1ME9tZDFaWE4wWW05dmF6cGtaV1poZFd4MEluMC5hSTJhTWRBR1JuNHVIZXFmcEY4Y2lOam1RXzA2U2RvZkVqajlOLXpRcXkzS3ZSdmhfd1AwYUlNSGdsOW9Pb2Mzc01rdVJtMlFkOXctWGNVM0xSbTRtVmlka2t2M2E2X0NwNGZFZ25hSk9QT1BIRmlxQWI3RUJMdk5Idzd5amNYYTBrUVVHdWxmUjVlQkZkWTBXcFZRc2dtRXQtcnkzZFNPNFo2UG1RWHA5a2Y4QnhSMTRudS1CekRBYjQzUkwwdjByUF9PSjRMc2NzUloyaVFMZi00TTVxTU9FcnJDM05fbHlmZ2NyOFdwNEFsbUtYaU5XekVGSkp1eVk3aS11QUI0TjBKeGhtUnZUU0dFTHZhUnBVaTBPN09lbkllbHZXMmpBR0t5T3RqcTVjanYwUHh1LWtfNUQzUm9ZYk14VnAyRHhKeWFQN3V3Rjc3Xy02VzVyZC1YLXc=
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: default
    kubernetes.io/service-account.uid: 361fd010-de74-46ea-b32b-7f7f0da35e71
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:ca.crt: {}
        f:namespace: {}
        f:token: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubernetes.io/service-account.name: {}
          f:kubernetes.io/service-account.uid: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-01-31T20:24:59Z"
  name: default-token-7wq5b
  namespace: guestbook
type: kubernetes.io/service-account-token
